jwt:
  secret: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
  expiration: 2592000
  maxToken: 3
security:
  secret-key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC50cddz0u1w7mv
    Zg57uMM6cS8W+yp1cMMWeqKrsY125rQzvtlDGO+XHEfAFg5kRLLMngN4Z6bnBdyO
    TaCh8zUcHo6nZaAEXykZ0KYRKEajnhYDDPhgdwe7yXrMqArauY1jO/JEQ7NUcqQq
    JzXxFnqd49YmH/B65hE4jrF4O2Xr1SmguvYSqjNfItajm49k0Djo2blA9OcC15aG
    njuFE7VPUKRwbGvFGZ0pBBDQIfpFNIYVh2Sx5CeMdxj9YdJHRvGvHd0S1KZcxOqz
    imjirZoMSUUhEl1MiYVjXtyu5unBN2JOe4b4THahlRfX3bEPhuQ9NpPdXl6cS/pB
    kyskXFdVAgMBAAECggEAANGya2Qlcf5g/EUOALCehH+8Oxs0I2llJF1TbnNT0gR2
    IrMPYFLYHe/p4KhlCHJSR9s7qhVQfVZsYJPQbSmJZrLU/FrsoVuA1S3/+88tviOA
    kFatzGsQTynpTyty3maQzErjqGmUY382RwzkmXsr/JplA5NpEXmf9Zv3bBxchVu2
    XkEUz5BoxX5S3peAMMC8u8CKJsCMSbgbPnFxloJTkClA5PxYGNwp4rHeKYTzHkPe
    l0r4Si3jjdOXmXzbi72YaS5yjKVuwcWYnO8l57IirN+eJcrjUVPmKgUj8nkPlD4T
    cULl76niIYi+FWSL8La4366HcEDxZMjVzUVk7w16LwKBgQDu5IRKzaZ2MqVSEciH
    TSnxxs/JpfaIkqL0rGDOkIYsTD7X+Z99xEoCY5jSino7fuu2KWk5FYe9F7r4VxiJ
    zUlA/RxiXYyedkKZPZbC7rA7+CVgC1mOCt//gePH/KLOAb2TU1NWVnlMJH8acOen
    KJ5+PdS6yvO/QJOVqFpt5pfMLwKBgQDHIE0ebMiab3w4tDtuqFQO37E7du3Z/hQO
    RQdBk8agPUXabhUTN25ErVuY2Ews/qcLrh/H4PcxBZMTuuHX2i/jOYfJqsChBJcR
    GgHKmXsiK0YrQaRUx+T9IrH176rDfMp1czCy7PNWP1jJnx1DtksI3Ojf6Q0YSg+Z
    Z95DF6efuwKBgQC3BueAdC0cE9NrnGpZlzoSnjKmmPvYSRiGgucse7gAim3/hKW4
    csINMIduj1/041nuV63haWh07JB4IiqPsXN1UjcD+g55fbuqsnAmaz8kwwrHmgqD
    9DsIBFki6KFHWjgHfuizlk8akj+7X1NsU4eSywaIEmRLXEt2duTJnMkiSwKBgQCo
    uioembbxhX4Q3kdt4Jw5bjpTVNb+XFjKLpuTaZBovwKtr5GUEugQsYRn4v/JMI6D
    SywKxgkvNLYHhddQe8UQGPOCYnmO9sC68PqLnbnEnj568Mg6Ppc+F2QMLOTZeKhl
    FRIyyqz2a/7j+Ttm4NR70hRRhrxd1IObTXP8DdMveQKBgQC5u+Jz627OGKzaYd9J
    GLUX5Rf8wl+J7DRQJlJhS1A6EY/BmNxUwch394/vh5Pb9ulrTAHow6kOD8RkJA8P
    I7ikrZ7RE8acbEL0ek7WA0isxlEZW2srQMZyiVZ8FKakEv+hETcxh1fefS1BqIDH
    LuYlWqYPmMWOK9dDx4ciw9y4eg==
    -----END PRIVATE KEY-----
# spring:
#   application:
#     name: common-service
